# micro-ota bootstrap boot.py – generated by uota bootstrap
import boot_guard
boot_guard.boot()

import _thread

def _ota():
    try:
        from ota import OTAUpdater
        upd = OTAUpdater()
        import boot_guard as _bg
        _bg.mark_clean()
        upd.run()
    except Exception as _e:
        print('[OTA] Failed to start:', _e)

_thread.start_new_thread(_ota, ())

# Give the OTA thread time to connect WiFi before main.py starts
import time
time.sleep(6)
