# micro-ota boot.py — generated by uota bootstrap / uota init
# Do not edit by hand; re-run bootstrap to regenerate.
import sys
if '/lib/uota' not in sys.path:
    sys.path.insert(0, '/lib/uota')

import boot_guard
from ota import OTAUpdater
boot_guard.boot()

OTAUpdater.activate_hardware()

# Launch the user application in a dedicated thread so it runs concurrently
# with the OTA server.  8 KB stack is sufficient for a simple app loop.
import _thread
def _run_app():
    try:
        if '/app' not in sys.path:
            sys.path.insert(0, '/app')
        import app as _app
        _app.run()
    except Exception as _e:
        print('[App] Error:', _e)
_thread.stack_size(8 * 1024)
_thread.start_new_thread(_run_app, ())

try:
    upd = OTAUpdater()
    import boot_guard as _bg; _bg.mark_clean()
    upd.run()
except Exception as _e:
    print('[OTA] Fatal error:', _e)
