# micro-ota boot.py — serial transport
# Generated by: uota bootstrap
from uota import boot_guard
boot_guard.boot()

import _thread

def _ota():
    try:
        from uota.ota import OTAUpdater
        upd = OTAUpdater()
        from uota import boot_guard as _bg
        _bg.mark_clean()
        upd.run()
    except Exception as _e:
        print('[OTA] Failed to start:', _e)

_thread.start_new_thread(_ota, ())

import time
time.sleep(3)
