# micro-ota boot.py — generated by uota bootstrap / uota init
# Do not edit by hand; re-run bootstrap to regenerate.
import sys
if '/lib/uota' not in sys.path:
    sys.path.insert(0, '/lib/uota')

import boot_guard
from ota import OTAUpdater
boot_guard.boot()

OTAUpdater.activate_hardware()

import _thread

def _ota():
    try:
        upd = OTAUpdater()
        import boot_guard as _bg; _bg.mark_clean()
        upd.run()
    except Exception as _e:
        print('[OTA] Failed to start:', _e)

def _remoteio():
    try:
        import remoteio
        remoteio.run()
    except Exception as _e:
        print('[RemoteIO] Failed to start:', _e)

_thread.stack_size(8192)
_thread.start_new_thread(_ota, ())
_thread.stack_size(4096)
_thread.start_new_thread(_remoteio, ())
