"""
First-time bootstrap: uploads the OTA library to a blank ESP32 via serial.

Files uploaded to the device (paths relative to project root → device path):
  device/ota.py                       → /ota.py
  device/boot_guard.py                → /boot_guard.py
  device/transports/__init__.py       → /transports/__init__.py
  device/transports/wifi_tcp.py       → /transports/wifi_tcp.py
  ota.json                            → /ota.json
  (generated)                         → /boot.py
"""

import os
import sys

# Files to upload: (host_relative_path, device_absolute_path)
_DEVICE_FILES = [
    ('device/ota.py',                     '/ota.py'),
    ('device/boot_guard.py',              '/boot_guard.py'),
    ('device/transports/__init__.py',     '/transports/__init__.py'),
    ('device/transports/wifi_tcp.py',     '/transports/wifi_tcp.py'),
    ('ota.json',                          '/ota.json'),
]

_BOOT_PY = '''\
# micro-ota bootstrap boot.py – generated by uota bootstrap
import boot_guard
boot_guard.boot()

import _thread

def _ota():
    try:
        from ota import OTAUpdater
        upd = OTAUpdater()
        import boot_guard as _bg
        _bg.mark_clean()
        upd.run()
    except Exception as _e:
        print('[OTA] Failed to start:', _e)

_thread.start_new_thread(_ota, ())

# Give the OTA thread time to connect WiFi before main.py starts
import time
time.sleep(6)
'''


def run(port, baud=115200, project_root=None):
    """Bootstrap the device on *port* with *baud* baud rate."""
    from host.transports.serial import RawREPL, auto_detect_port

    if project_root is None:
        project_root = _find_project_root()

    if port is None:
        port = auto_detect_port()
        if port is None:
            print('ERROR: No serial port found. Connect the device and retry,')
            print('       or specify --port explicitly.')
            sys.exit(1)
        print('Auto-detected port:', port)

    print('Bootstrapping {} @ {} baud ...'.format(port, baud))

    with RawREPL(port, baud) as repl:
        for local_rel, remote in _DEVICE_FILES:
            local = os.path.join(project_root, local_rel)
            if not os.path.exists(local):
                print('  [skip] {} not found'.format(local_rel))
                continue
            print('  {:<45} → {}'.format(local_rel, remote))
            repl.put_file(local, remote, on_progress=_progress(local_rel))

        print('  {:<45} → /boot.py'.format('(generated boot.py)'))
        repl.write_text('/boot.py', _BOOT_PY)

        print('\nBootstrap complete. Resetting device ...')
        repl.soft_reset()

    print('Done. Device is now OTA-capable.')
    print('Next step: run  uota fast  to upload your application.')


# ── helpers ───────────────────────────────────────────────────────────────────

def _find_project_root():
    """Walk up from this file until we find ota.json."""
    d = os.path.dirname(os.path.abspath(__file__))
    for _ in range(5):
        if os.path.exists(os.path.join(d, 'ota.json')):
            return d
        d = os.path.dirname(d)
    return os.getcwd()


def _progress(name):
    last = [-1]
    def cb(sent, total):
        pct = int(sent / total * 100) if total else 100
        if pct != last[0]:
            last[0] = pct
            bar = '#' * (pct // 5) + '-' * (20 - pct // 5)
            print('\r    [{}] {:3d}%'.format(bar, pct), end='', flush=True)
        if sent == total:
            print()
    return cb
