# micro-ota boot.py — generated by uota bootstrap / uota init
# Do not edit by hand; re-run bootstrap to regenerate.
import sys
if '/lib/uota' not in sys.path:
    sys.path.insert(0, '/lib/uota')

import boot_guard
from ota import OTAUpdater
boot_guard.boot()

OTAUpdater.activate_hardware()

# Only spawn the RemoteIO thread if remoteioPort is configured and non-zero.
# With BLE+WiFi coexistence active the free heap is tight; skipping this thread
# when unused saves the stack + TCB overhead (~6-8 KB on ESP32).
try:
    import json as _j
    with open('/config/ota.json') as _f:
        _rio_port = _j.load(_f).get('remoteioPort', 0)
except Exception:
    _rio_port = 0

if _rio_port:
    import _thread

    def _remoteio():
        try:
            import remoteio
            remoteio.run(_rio_port)
        except Exception as _e:
            print('[RemoteIO] Failed to start:', _e)

    try:
        _thread.stack_size(4096)
        _thread.start_new_thread(_remoteio, ())
    except OSError:
        print('[boot] Not enough heap for RemoteIO thread — skipped')

# Run OTA in the main thread (no extra thread, no extra stack allocation).
# machine.reset() inside the OTA handler terminates this naturally.
try:
    upd = OTAUpdater()
    import boot_guard as _bg; _bg.mark_clean()
    upd.run()
except Exception as _e:
    print('[OTA] Fatal error:', _e)
