"""
First-time bootstrap: uploads the OTA library to a blank ESP32 via serial.

Device files are taken from:
  1. <project>/device/  (if present — created by `uota init`)
  2. The bundled _device/ folder inside this package (fallback)

Files uploaded:
  ota.py, boot_guard.py, remoteio.py, transports/__init__.py,
  transports/wifi_tcp.py, ota.json (from project), boot.py (generated)
"""

import os
import sys
from pathlib import Path

_BUNDLED = Path(__file__).parent / '_device'

_DEVICE_RELPATHS = [
    ('ota.py',                    '/ota.py'),
    ('boot_guard.py',             '/boot_guard.py'),
    ('remoteio.py',               '/remoteio.py'),
    ('transports/__init__.py',    '/transports/__init__.py'),
    ('transports/wifi_tcp.py',    '/transports/wifi_tcp.py'),
]

_BOOT_PY = '''\
# micro-ota bootstrap boot.py – generated by uota bootstrap
import boot_guard
boot_guard.boot()

import _thread

def _ota():
    try:
        from ota import OTAUpdater
        upd = OTAUpdater()
        import boot_guard as _bg
        _bg.mark_clean()
        upd.run()
    except Exception as _e:
        print('[OTA] Failed to start:', _e)

def _remoteio():
    try:
        import remoteio
        remoteio.run()
    except Exception as _e:
        print('[RemoteIO] Failed to start:', _e)

_thread.start_new_thread(_ota, ())
_thread.start_new_thread(_remoteio, ())

import time
time.sleep(6)
'''


def run(port, baud=115200, device_dir=None):
    """
    Bootstrap the device on *port*.

    device_dir — directory containing OTA device files.
                 Defaults to <cwd>/device if it exists, otherwise the
                 bundled _device/ folder from the package.
    """
    from .transports.serial import RawREPL, auto_detect_port

    # Resolve device source directory
    if device_dir is None:
        cwd_device = Path.cwd() / 'device'
        device_dir = cwd_device if cwd_device.is_dir() else _BUNDLED

    device_dir = Path(device_dir)
    print('[bootstrap] Using device files from:', device_dir)

    if port is None:
        port = auto_detect_port()
        if port is None:
            print('ERROR: No serial port found. Connect the device and retry,')
            print('       or specify --port explicitly.')
            sys.exit(1)
        print('Auto-detected port:', port)

    print('Bootstrapping {} @ {} baud …'.format(port, baud))

    with RawREPL(port, baud) as repl:
        # Upload OTA infrastructure files
        for rel, remote in _DEVICE_RELPATHS:
            local = device_dir / rel
            if not local.exists():
                print('  [skip] {} not found'.format(rel))
                continue
            print('  {:<45} → {}'.format(rel, remote))
            repl.put_file(str(local), remote, on_progress=_progress(rel))

        # Upload ota.json from the project (current dir)
        ota_json = Path.cwd() / 'ota.json'
        if ota_json.exists():
            print('  {:<45} → /ota.json'.format('ota.json'))
            repl.put_file(str(ota_json), '/ota.json', on_progress=_progress('ota.json'))
        else:
            print('  [skip] ota.json not found in current directory')

        # Write generated boot.py
        print('  {:<45} → /boot.py'.format('(generated boot.py)'))
        repl.write_text('/boot.py', _BOOT_PY)

        print('\nBootstrap complete. Resetting device …')
        repl.soft_reset()

    print('Done. Device is now OTA-capable.')
    print('Next step: run  uota fast  to upload your application.')


def _progress(name):
    last = [-1]
    def cb(sent, total):
        pct = int(sent / total * 100) if total else 100
        if pct != last[0]:
            last[0] = pct
            bar = '#' * (pct // 5) + '-' * (20 - pct // 5)
            print('\r    [{}] {:3d}%'.format(bar, pct), end='', flush=True)
        if sent == total:
            print()
    return cb
