#!/usr/bin/env python3
"""
uota – micro-ota host CLI

Commands:
  init       [--dir DIR] [--force]
  bootstrap  [--port PORT] [--baud BAUD]
  fast        [--host HOST] [--port PORT] [--transport T] [--version VER]
  full        [--host HOST] [--port PORT] [--transport T] [--version VER] [--wipe]
  terminal    [--host HOST] [--port PORT] [--transport T]
  version     [--host HOST] [--port PORT] [--transport T]
  flash <firmware.bin> [--port PORT] [--baud BAUD] [--chip CHIP] [--erase]
  serve       [--host HOST] [--port PORT] [--version VER]
  bundle      [--out DIR] [--zip] [--version VER]
  remoteio    listen | call <name> [key=val ...]

All connection params default to values in ota.json when not specified.
"""

import argparse
import errno
import json
import os
import sys
import socket
import time
from pathlib import Path

from .manifest import build as build_manifest, to_json as manifest_to_json, sign as sign_manifest
from .transports.wifi_tcp import WiFiTCPTransport
from .transports.serial import SerialOTATransport


# ── boot.py template written by init + bootstrap ─────────────────────────────

_BOOT_PY = '''\
# micro-ota boot.py – generated by uota init
import boot_guard
boot_guard.boot()

import _thread

def _ota():
    try:
        from ota import OTAUpdater
        upd = OTAUpdater()
        import boot_guard as _bg
        _bg.mark_clean()
        upd.run()
    except Exception as _e:
        print('[OTA] Failed to start:', _e)

def _remoteio():
    try:
        import remoteio
        remoteio.run()
    except Exception as _e:
        print('[RemoteIO] Failed to start:', _e)

_thread.start_new_thread(_ota, ())
_thread.start_new_thread(_remoteio, ())

import time
time.sleep(6)
'''


# ── error handling ────────────────────────────────────────────────────────────

def _friendly(exc, cfg=None):
    msg = str(exc)
    eno = getattr(exc, 'errno', None)

    try:
        import serial
        if isinstance(exc, serial.SerialException):
            if 'No such file' in msg or 'cannot find' in msg.lower():
                port = msg.split("'")[1] if "'" in msg else msg
                return ("Serial port not found: {}\n"
                        "  Check the USB cable or set serialPort in ota.json.").format(port)
            if 'Permission denied' in msg or 'Access is denied' in msg:
                port = msg.split("'")[1] if "'" in msg else '(port)'
                return ("Permission denied on {}.\n"
                        "  Run: sudo usermod -aG dialout $USER  then log out and back in.\n"
                        "  Or prefix your command with: sg dialout -c \"...\"").format(port)
            return 'Serial error: ' + msg
    except ImportError:
        pass

    if isinstance(exc, (TimeoutError, socket.timeout)):
        host = cfg.get('hostname', '?') if cfg else '?'
        port = cfg.get('port', 2018) if cfg else '?'
        return ("Timed out connecting to {}:{}.\n"
                "  Is the device on WiFi and is the OTA server running?").format(host, port)

    if isinstance(exc, ConnectionRefusedError) or eno == errno.ECONNREFUSED:
        host = cfg.get('hostname', '?') if cfg else '?'
        port = cfg.get('port', 2018) if cfg else '?'
        return ("Connection refused at {}:{}.\n"
                "  The OTA server may not have started yet — wait a few seconds and retry.\n"
                "  Or run: uota terminal  to check device state.").format(host, port)

    if eno in (errno.ENETUNREACH, errno.EHOSTUNREACH, errno.ENETDOWN):
        return ("Network unreachable. Check that the host and device are on the same network\n"
                "  and that hostname/IP in ota.json is correct.")

    if isinstance(exc, OSError):
        if eno == errno.EIO:
            return 'I/O error on serial port. Device disconnected during transfer?'
        if eno == errno.ENOENT:
            return 'Device or file not found: ' + msg
        if 'connection closed' in msg.lower():
            return ('Device closed the connection unexpectedly.\n'
                    '  It may have reset mid-transfer — check the serial console.')

    if isinstance(exc, RuntimeError):
        if 'raw REPL' in msg:
            return ("Could not enter MicroPython raw REPL.\n"
                    "  Press the Reset button on the device and retry.\n"
                    "  Detail: " + msg)
        if 'Inline OTA' in msg or 'failed to start' in msg.lower():
            return ("Serial OTA server injection failed.\n"
                    "  Reset the device and retry: uota fast --transport serial\n"
                    "  Detail: " + msg)
        if 'not ready' in msg or 'ready' in msg:
            return 'Device rejected OTA session: ' + msg
        if 'No OTA transport' in msg or 'No supported transport' in msg:
            return ("No transport configured.\n"
                    "  Set 'transports' in ota.json (e.g. [\"wifi_tcp\"] or [\"serial\"]).")
        if 'bleak is required' in msg:
            return msg   # already has pip install hint
        return 'Error: ' + msg

    if isinstance(exc, FileNotFoundError):
        return 'File not found: ' + msg

    if 'BLE' in msg or 'bluetooth' in msg.lower():
        return 'BLE error: ' + msg

    return None


# ── config ────────────────────────────────────────────────────────────────────

def load_config(path='ota.json'):
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        return {}


# ── transport factory ─────────────────────────────────────────────────────────

def get_transport(cfg, host_override=None, port_override=None, transport_override=None):
    names = [transport_override] if transport_override else cfg.get('transports', ['wifi_tcp'])

    for name in names:
        if name == 'wifi_tcp':
            host = host_override or cfg.get('hostname', 'micropython')
            port = port_override or cfg.get('port', 2018)
            return WiFiTCPTransport(host, port)
        if name == 'serial':
            port = host_override or cfg.get('serialPort') or _auto_serial()
            baud = cfg.get('serialBaud', 115200)
            return SerialOTATransport(port, baud)
        if name == 'ble':
            from .transports.ble import BLETransport
            ble_name = host_override or cfg.get('bleName', 'micro-ota')
            return BLETransport(ble_name)

    raise RuntimeError('No supported transport in config')


def _auto_serial():
    from .transports.serial import auto_detect_port
    p = auto_detect_port()
    if p is None:
        print('ERROR: No serial port found. Connect the device or set serialPort in ota.json.')
        sys.exit(1)
    return p


# ── OTA push ──────────────────────────────────────────────────────────────────

def send_ota(transport, files, manifest, wipe=False):
    start = time.time()
    with transport:
        if wipe:
            transport.connect()
            transport.write_line('wipe')
            resp = transport.read_line()
            if resp.strip() != 'ok':
                print('Wipe failed:', resp)
                sys.exit(1)
            print('Device wiped.')
            transport.close()
            time.sleep(1)
            transport.connect()

        transport.write_line('start_ota')
        resp = transport.read_line()
        if resp.strip() != 'ready':
            print('Device not ready:', resp)
            sys.exit(1)

        m_json = manifest_to_json(manifest).encode()
        transport.write_line('manifest {}'.format(len(m_json)))
        transport.write(m_json)
        resp = transport.read_line()
        if resp.strip() != 'ok':
            print('Manifest rejected:', resp)
            transport.write_line('abort')
            sys.exit(1)

        total_files = len(files)
        for i, (rel_path, abs_path) in enumerate(files.items(), 1):
            info   = manifest['files'][rel_path]
            size   = info['size']
            sha256 = info['sha256']

            print('  [{}/{}] {}'.format(i, total_files, rel_path), end='  ', flush=True)
            transport.write_line('file {};{};{}'.format(rel_path, size, sha256))

            sent = 0
            t0   = time.time()
            with open(abs_path, 'rb') as f:
                while True:
                    chunk = f.read(4096)
                    if not chunk:
                        break
                    transport.write(chunk)
                    sent += len(chunk)

            resp    = transport.read_line().strip()
            elapsed = time.time() - t0
            speed   = (size / 1024) / elapsed if elapsed > 0 else 0
            if resp == 'ok':
                print('{:.1f} KB/s'.format(speed))
            else:
                print('\nFailed:', resp)
                transport.write_line('abort')
                sys.exit(1)

        transport.write_line('end_ota')
        resp = transport.read_line()
        if resp.strip() == 'ok':
            elapsed = time.time() - start
            print('\nOTA done in {:.1f}s  ({} files)'.format(elapsed, total_files))


# ── commands ──────────────────────────────────────────────────────────────────

def cmd_init(args, cfg):
    """Initialize a new micro-ota project in the target directory."""
    import shutil

    target = Path(getattr(args, 'dir', None) or '.').resolve()
    target.mkdir(parents=True, exist_ok=True)
    force  = getattr(args, 'force', False)

    # 1. Copy device OTA infrastructure files
    device_src = Path(__file__).parent / '_device'
    device_dst = target / 'device'
    if device_dst.exists() and not force:
        print('[init] device/ already exists — skipping (use --force to overwrite)')
    else:
        if device_dst.exists():
            shutil.rmtree(device_dst)
        shutil.copytree(device_src, device_dst,
                        ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '*.pyo'))
        print('[init] Copied OTA device files → device/')

    # 2. Create ota.json
    ota_json = target / 'ota.json'
    if not ota_json.exists():
        default = {
            "version":      "1.0.0",
            "hostname":     "192.168.1.100",
            "port":         2018,
            "remoteioPort": 2019,
            "ssid":         "",
            "password":     "",
            "otaKey":       "",
            "bleName":      "micro-ota",
            "serialPort":   "",
            "transports":   ["wifi_tcp"],
            "manifestUrl":  "",
            "pullInterval": 60,
            "excludedFiles": [
                ".git/**", "device/**", "*.zip", "dist/**"
            ],
            "fastOtaFiles": ["main.py"],
            "fullOtaFiles": ["*.py", "lib/**", "*.json"],
        }
        with open(ota_json, 'w') as f:
            json.dump(default, f, indent=4)
        print('[init] Created ota.json')
    else:
        print('[init] ota.json already exists — skipping')

    # 3. Create stub main.py
    main_py = target / 'main.py'
    if not main_py.exists():
        main_py.write_text('# Your application\nprint("Hello from MicroPython!")\n')
        print('[init] Created main.py')

    # 4. Create boot.py
    boot_py = target / 'boot.py'
    if not boot_py.exists():
        boot_py.write_text(_BOOT_PY)
        print('[init] Created boot.py')

    print('\nDone! Next steps:')
    print('  1. Edit ota.json — fill in ssid, password, hostname')
    print('  2. Connect your ESP32 via USB')
    print('  3. Run: uota bootstrap   (first-time device setup)')
    print('  4. Run: uota fast        (push app updates)')


def cmd_bootstrap(args, cfg):
    from .bootstrap import run as do_bootstrap
    do_bootstrap(
        port=args.port or cfg.get('serialPort'),
        baud=args.baud,
        mpy=args.mpy,
    )


def cmd_fast(args, cfg):
    patterns  = cfg.get('fastOtaFiles', ['main.py'])
    excludes  = cfg.get('excludedFiles', [])
    version   = args.version or cfg.get('version', 'unknown')
    manifest  = build_manifest(patterns, excludes, version)
    key = cfg.get('otaKey', '')
    if key:
        manifest = sign_manifest(manifest, key)
        print('Manifest signed (HMAC-SHA256).')
    files     = {p: p for p in manifest['files']}
    transport = get_transport(cfg, args.host, args.port, getattr(args, 'transport', None))
    print('Fast OTA: {} file(s)'.format(len(files)))
    send_ota(transport, files, manifest)


def cmd_full(args, cfg):
    patterns  = cfg.get('fastOtaFiles', []) + cfg.get('fullOtaFiles', [])
    excludes  = cfg.get('excludedFiles', [])
    version   = args.version or cfg.get('version', 'unknown')
    manifest  = build_manifest(patterns, excludes, version)
    key = cfg.get('otaKey', '')
    if key:
        manifest = sign_manifest(manifest, key)
        print('Manifest signed (HMAC-SHA256).')
    files     = {p: p for p in manifest['files']}
    transport = get_transport(cfg, args.host, args.port, getattr(args, 'transport', None))
    print('Full OTA: {} file(s){}'.format(len(files), '  [wipe first]' if args.wipe else ''))
    send_ota(transport, files, manifest, wipe=args.wipe)


def cmd_terminal(args, cfg):
    transport = get_transport(cfg, args.host, args.port, getattr(args, 'transport', None))
    print("Terminal mode. Type 'exit' to quit.")
    print("Commands: ping, version, ls [path], get <path>, rm <path>, reset, wipe")
    while True:
        try:
            line = input('$ ').strip()
        except (EOFError, KeyboardInterrupt):
            break
        if not line or line.lower() in ('exit', 'quit'):
            break
        try:
            with transport:
                transport.write_line(line)
                if line.startswith('get '):
                    size_line = transport.read_line()
                    try:
                        size = int(size_line.strip())
                        data = transport.read_exact(size)
                        sys.stdout.buffer.write(data)
                        sys.stdout.buffer.flush()
                        print()
                    except ValueError:
                        print(size_line)
                else:
                    print(transport.read_line())
        except OSError as e:
            print('Connection error:', e)


def cmd_version(args, cfg):
    transport = get_transport(cfg, args.host, args.port, getattr(args, 'transport', None))
    with transport:
        transport.write_line('version')
        print(transport.read_line())


def cmd_flash(args, cfg):
    from .firmware import flash, _find_port
    port = args.port or _find_port(cfg)
    flash(
        firmware_path=args.firmware,
        port=port,
        baud=args.baud,
        chip=args.chip,
        erase=args.erase,
    )


def cmd_serve(args, cfg):
    from .serve import serve
    serve(
        host=args.host,
        port=args.port,
        version=args.version or cfg.get('version'),
    )


def cmd_bundle(args, cfg):
    from .bundle import build
    build(
        out_dir=args.out,
        make_zip=args.zip,
        version=args.version or cfg.get('version'),
    )


def cmd_remoteio(args, cfg):
    """Delegate to the remoteio CLI."""
    from .remoteio import main as remoteio_main
    # Reconstruct argv so remoteio.main() sees it
    argv = [args.subcmd] + (args.remoteio_args or [])
    sys.argv = ['uota remoteio'] + argv
    remoteio_main()


# ── CLI entry point ───────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(
        prog='uota',
        description='micro-ota host tool',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument('-v', '--verbose', action='store_true',
                   help='Show full traceback on errors')
    sub = p.add_subparsers(dest='command', required=True)

    # init
    ini = sub.add_parser('init', help='Initialize a new micro-ota project')
    ini.add_argument('--dir',   default='.', help='Target directory (default: current dir)')
    ini.add_argument('--force', action='store_true', help='Overwrite existing device/ files')

    # bootstrap
    bs = sub.add_parser('bootstrap', help='First-time upload of OTA lib via serial')
    bs.add_argument('--port', help='Serial port (auto-detected if omitted)')
    bs.add_argument('--baud', type=int, default=115200)
    bs.add_argument('--mpy', action='store_true',
                    help='Compile OTA files to .mpy with mpy-cross (faster import, less RAM)')

    # fast
    fa = sub.add_parser('fast', help='Push fastOtaFiles to the device')
    fa.add_argument('--host')
    fa.add_argument('--port',      type=int)
    fa.add_argument('--version')
    fa.add_argument('--transport', choices=['wifi_tcp', 'serial', 'ble'])

    # full
    fu = sub.add_parser('full', help='Push all managed files to the device')
    fu.add_argument('--host')
    fu.add_argument('--port', type=int)
    fu.add_argument('--version')
    fu.add_argument('--wipe', action='store_true')
    fu.add_argument('--transport', choices=['wifi_tcp', 'serial', 'ble'])

    # terminal
    te = sub.add_parser('terminal', help='Interactive device terminal')
    te.add_argument('--host')
    te.add_argument('--port', type=int)
    te.add_argument('--transport', choices=['wifi_tcp', 'serial', 'ble'])

    # version
    ve = sub.add_parser('version', help='Read version from device')
    ve.add_argument('--host')
    ve.add_argument('--port', type=int)
    ve.add_argument('--transport', choices=['wifi_tcp', 'serial', 'ble'])

    # flash
    fl = sub.add_parser('flash', help='Flash MicroPython firmware via esptool')
    fl.add_argument('firmware')
    fl.add_argument('--port',  default=None)
    fl.add_argument('--baud',  type=int, default=460800)
    fl.add_argument('--chip',  default='auto')
    fl.add_argument('--erase', action='store_true')

    # serve
    sv = sub.add_parser('serve', help='HTTP server for http_pull transport')
    sv.add_argument('--host',    default='0.0.0.0')
    sv.add_argument('--port',    type=int, default=8080)
    sv.add_argument('--version', default=None)

    # bundle
    bu = sub.add_parser('bundle', help='Create a self-contained release bundle')
    bu.add_argument('--out',     default='dist')
    bu.add_argument('--zip',     action='store_true')
    bu.add_argument('--version', default=None)

    # remoteio
    rio = sub.add_parser('remoteio', help='RemoteIO side-channel (listen / call)')
    rio.add_argument('subcmd', choices=['listen', 'call'], help='listen or call')
    rio.add_argument('remoteio_args', nargs=argparse.REMAINDER)

    args = p.parse_args()
    cfg  = load_config()

    dispatch = {
        'init':      cmd_init,
        'bootstrap': cmd_bootstrap,
        'fast':      cmd_fast,
        'full':      cmd_full,
        'terminal':  cmd_terminal,
        'version':   cmd_version,
        'flash':     cmd_flash,
        'serve':     cmd_serve,
        'bundle':    cmd_bundle,
        'remoteio':  cmd_remoteio,
    }

    try:
        dispatch[args.command](args, cfg)
    except KeyboardInterrupt:
        print('\nInterrupted.', file=sys.stderr)
        sys.exit(130)
    except SystemExit:
        raise
    except Exception as exc:
        if args.verbose:
            raise
        eff = dict(cfg)
        if getattr(args, 'host', None):
            eff['hostname'] = args.host
        if getattr(args, 'port', None):
            eff['port'] = args.port
        friendly = _friendly(exc, eff)
        if friendly:
            print('ERROR:', friendly, file=sys.stderr)
        else:
            print('ERROR:', exc, file=sys.stderr)
            print('       Run with -v for the full traceback.', file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
