# micro-ota boot.py — generated by: uota init / uota bootstrap
# Copy this to the root of your MicroPython device filesystem.
from uota import boot_guard
boot_guard.boot()

import _thread

def _ota():
    try:
        from uota.ota import OTAUpdater
        upd = OTAUpdater()
        from uota import boot_guard as _bg
        _bg.mark_clean()
        upd.run()
    except Exception as _e:
        print('[OTA] Failed to start:', _e)

def _remoteio():
    try:
        from uota import remoteio
        remoteio.run()
    except Exception as _e:
        print('[RemoteIO] Failed to start:', _e)

_thread.start_new_thread(_ota, ())
_thread.start_new_thread(_remoteio, ())

# Give OTA/RemoteIO threads time to connect WiFi before main.py starts
import time
time.sleep(6)
